use clap::Command;
use std::fmt::Write;

pub(crate) struct GeneratedCliDoc {
    pub filename: String,
    pub command: String,
    pub markdown: String,
}

pub(crate) fn render_cli_markdown(mut root: Command) -> String {
    root.build();
    let mut output = String::from(
        "# rdevtool CLI Reference\n\n\
Generated from the Clap command definitions. Do not edit this file by hand.\n\n",
    );
    render_command(&root, &mut output, &[]);
    normalized_markdown(output)
}

pub(crate) fn render_cli_domain_docs(mut root: Command) -> Vec<GeneratedCliDoc> {
    root.build();
    let root_name = root.get_name().to_string();
    root.get_subcommands()
        .filter(|command| command.get_name() != "help" && !command.is_hide_set())
        .map(|command| {
            let command_name = command.get_name().to_string();
            let mut markdown = format!(
                "# `{} {}`\n\nGenerated from the Clap command definitions. Do not edit this file by hand.\n\n",
                root_name, command_name
            );
            render_command(command, &mut markdown, std::slice::from_ref(&root_name));
            GeneratedCliDoc {
                filename: format!("{}.md", normalized_filename(&command_name)),
                command: command_name,
                markdown: normalized_markdown(markdown),
            }
        })
        .collect()
}

fn normalized_markdown(markdown: String) -> String {
    format!("{}\n", markdown.trim_end())
}

fn render_command(command: &Command, output: &mut String, parents: &[String]) {
    let mut path = parents.to_vec();
    path.push(command.get_name().to_string());
    let level = path.len().min(6);
    let _ = writeln!(output, "{} `{}`\n", "#".repeat(level), path.join(" "));
    if let Some(about) = command.get_long_about().or_else(|| command.get_about()) {
        let _ = writeln!(output, "{}\n", about);
    }

    let mut help_command = command.clone();
    let help = help_command
        .render_long_help()
        .to_string()
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n");
    let _ = writeln!(output, "```text\n{}\n```\n", help.trim_end());

    for subcommand in command
        .get_subcommands()
        .filter(|command| command.get_name() != "help" && !command.is_hide_set())
    {
        render_command(subcommand, output, &path);
    }
}

fn normalized_filename(command: &str) -> String {
    command
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() || character == '-' {
                character
            } else {
                '-'
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::{render_cli_domain_docs, render_cli_markdown};
    use clap::{Arg, Command};

    #[test]
    fn renders_nested_commands_and_flags() {
        let command = Command::new("demo")
            .subcommand(Command::new("build").arg(Arg::new("compact").long("compact")));
        let output = render_cli_markdown(command);
        assert!(output.contains("# `demo`"));
        assert!(output.contains("## `demo build`"));
        assert!(output.contains("--compact"));
    }

    #[test]
    fn splits_top_level_domains_and_omits_help_mirrors() {
        let command =
            Command::new("demo").subcommand(Command::new("build").subcommand(Command::new("run")));
        let docs = render_cli_domain_docs(command);
        assert_eq!(docs.len(), 1);
        assert_eq!(docs[0].filename, "build.md");
        assert!(docs[0].markdown.contains("demo build run"));
        assert!(!docs[0].markdown.contains("demo help"));
    }

    #[test]
    fn omits_hidden_compatibility_commands() {
        let command = Command::new("demo")
            .subcommand(Command::new("build"))
            .subcommand(Command::new("trigger").hide(true));
        let docs = render_cli_domain_docs(command);
        assert_eq!(docs.len(), 1);
        assert_eq!(docs[0].command, "build");
    }
}
